fau

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -40,12 +40,6 @@ jobs:
         with:
           clean: true
 
-      - name: Configure Git Line Endings
-        run: |
-          git config --global core.autocrlf false
-          git config --global core.eol lf
-          git checkout .
-
       - name: Normalize Line Endings
         run: find . -type f -exec dos2unix {} \;
 
@@ -58,7 +52,7 @@ jobs:
         run: |
           pip install --index-url 'https://:2024-01-10T23:12:19.504680Z@time-machines-pypi.sealsecurity.io/' -U wheel
           pip install --index-url 'https://:2024-01-10T23:12:19.504680Z@time-machines-pypi.sealsecurity.io/' -U setuptools
-          python -m pip install --index-url 'https://:2024-01-10T23:12:19.504680Z@time-machines-pypi.sealsecurity.io/'  -U pip
+          python -m pip install --index-url 'https://:2024-01-10T23:12:19.504680Z@time-machines-pypi.sealsecurity.io/' -U pip
 
       - name: Remove Old Tox Environment
         run: rm -rf .tox
@@ -68,3 +62,12 @@ jobs:
 
       - name: Run Tox Environment
         run: tox run -e ${{ matrix.tox }}
+
+      - name: Debug Corrupted Files
+        if: failure()
+        run: |
+          echo "Listing files in tox environment..."
+          ls -la .tox/${{ matrix.tox }}/lib/python*/site-packages/jinja2/
+          echo "Dumping compiler.py..."
+          cat .tox/${{ matrix.tox }}/lib/python*/site-packages/jinja2/compiler.py || echo "compiler.py not found!"
+          echo "End of compiler.py content."
